#!/bin/bash

mod_disk () {
  # Customizable configuration constants
  local -r DEFAULT_PRE=''
  local -r DEFAULT_SUF=''

  local -r pre="${1-${DEFAULT_PRE}}"
  local -r suf="${2-${DEFAULT_SUF}}"

  printf '%b' "${pre}"
  df -h | awk 'NR == 4 {printf "disk: %s", $3}'
  df -h | awk 'NR == 4 {printf " (free: %s)", $4}'
  printf '%b' "${suf}"
}
