#!/bin/bash

# Install 'exa' a more advanced list command 
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S exa --noconfirm
"

# Create .bashrc and aliases for basic ls commands
arch-chroot $FOLDER_MNT /bin/bash -c "
  echo 'if [ -f ~/.bashrc ]; then' > ~/.bash_profile
  echo '  . ~/.bashrc' >> ~/.bash_profile
  echo 'fi' >> ~/.bash_profile
  source ~/.bash_profile

  # Create bashrc
  echo \"alias ls='exa --icons'\" > ~/.bashrc
  echo \"alias la='ls -hal --git --octal-permissions --smart-group'\" >> ~/.bashrc
  echo \"alias lg='la --git-ignore'\" >> ~/.bashrc
"

# Install node manager
arch-chroot $FOLDER_MNT /bin/bash -c "
  curl -L https://bit.ly/n-install | bash -s -- -y 
  sed -i 's|\$HOME/n|\$HOME/.install/n|g' ~/.bashrc 

  n lts
  mv ~/n ~/$FOLDER_INSTALL/ 
"

# Install docker
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S docker --noconfirm
  systemctl start docker
  systemctl enable docker

  pacman -S docker-compose --noconfirm

  echo \"alias up='docker-compose up -d --build'\" >> ~/.bashrc
  echo \"alias down='docker-compose down'\" >> ~/.bashrc
  echo \"alias ld='docker ps'\" >> ~/.bashrc
  echo \"alias logs='docker-compose logs'\" >> ~/.bashrc
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  cp ~/.bashrc /home/$user/.bashrc
"
