#!/bin/bash

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------

source ../.common/configure
source partition
source terminal
source sound

# ------------------------------------------------------------------------------
# Setup 
# ------------------------------------------------------------------------------

configure_globals
update_packages

create_partitions
format_partitions
mount_partitions

install_terminal
install_sound

echo "Setup was successful"
