#!/bin/bash

# ------------------------------------------------------------------------------
# Debian
# ------------------------------------------------------------------------------

# Download source code
function download_neovim() {
  download_folder=$1
  config_folder=/home/$USER/.config

  mkdir -p "$config_folder"

  clone "https://github.com/neovim/neovim" "$download_folder"
  clone "https://github.com/devbysp/nvim" "$config_folder"

  cp -r "$config_folder" /root/.config
}

# Build from source
function build_neovim() {
  build_folder=$1
  cd "$build_folder"/neovim || exit 1

  # Build latest stable version
  git checkout stable
  make CMAKE_BUILD_TYPE=RelWithDebInfo
  make clean install
}

# Build applications from source
function install_neovim_debian() {
  orig_path=$(pwd)
  build_folder=/home/$USER/.install

  mkdir -p "$build_folder"

  download_neovim "$build_folder"
  build_neovim "$build_folder"

  cd "$orig_path" || exit 1
}

# ------------------------------------------------------------------------------
# Arch
# ------------------------------------------------------------------------------

# Install app
function install_neovim_arch() {
  install "neovim"
}

# ------------------------------------------------------------------------------
# Install script
# ------------------------------------------------------------------------------

function install_neovim() {
  [[ $LINUX == "debian" ]] && install_neovim_debian
  [[ $LINUX == "arch" ]] && install_neovim_arch
}
