#!/bin/bash

# Download source code
function download_neovim() {
  local download_folder=$1
  local config_folder=/home/$USER/.config

  mkdir -p $config_folder

  clone "https://github.com/neovim/neovim" $download_folder
  clone "https://github.com/devbysp/nvim" $config_folder

  cp -r $config_folder /root/.config
}

# Build from source 
function build_neovim() {
  local build_folder=$1

  cd $build_folder/neovim

  # Build latest stable version
  git checkout stable
  make CMAKE_BUILD_TYPE=RelWithDebInfo
  make clean install
}

# Build applications from source
function install_neovim() {
  local orig_path=$(pwd)
  local build_folder=/home/$USER/.install

  mkdir -p $build_folder

  download_neovim $build_folder
  build_neovim $build_folder

  cd $orig_path
}
