#!/bin/bash

function install_nodejs() {
  # TODO: Install nodejs and npm with n-install

  # Install nodejs and node package manager
  install "nodejs npm"

  # Install some default libraries
  npm install -g typescript
}
