#!/bin/bash

# Copy linux install
mkdir -p        $FOLDER_MNT/home/$user/$FOLDER_INSTALL
mkdir -p        $FOLDER_MNT/home/$user/$FOLDER_CONFIG

cp -r ~/linux   $FOLDER_MNT/home/$user/$FOLDER_INSTALL

# Neovim config
git clone https://github.com/devbysp/nvim   $FOLDER_MNT/root/$FOLDER_INSTALL/nvim
arch-chroot $FOLDER_MNT /bin/bash -c "
  ln -s /root/$FOLDER_INSTALL/nvim          /root/$FOLDER_CONFIG/nvim
  chmod 764                                 /root/$FOLDER_CONFIG/nvim
"

cp -r $FOLDER_MNT/root/$FOLDER_INSTALL/*    $FOLDER_MNT/home/$user/$FOLDER_INSTALL/
arch-chroot $FOLDER_MNT /bin/bash -c "
  ln -s /home/$user/$FOLDER_INSTALL/nvim    /home/$user/$FOLDER_CONFIG/nvim
  chmod 764                                 /root/$FOLDER_CONFIG/nvim
"

# ------------------------------------------------------------------------------
# Destination location
mkdir -p $FOLDER_MNT/$FOLDER_BACKGROUND_IMGS

# Profile specific background image
PROFILE_BACKGROUND_IMG=home/profiles/$profile/$FOLDER_CONFIG/$FILE_DESKTOP_IMAGE

# Is there a profile specific background image provided
if [[ -e $PROFILE_BACKGROUND_IMG ]]; then
  # Copy profile specific background
  cp $PROFILE_BACKGROUND_IMG  $FOLDER_MNT/$FOLDER_BACKGROUND_IMGS/
else
  # Copy common background image to destination
  COMMON_BACKGROUND_IMG=home/common/$gui/$FOLDER_CONFIG/$FILE_DESKTOP_IMAGE
  cp $COMMON_BACKGROUND_IMG   $FOLDER_MNT/$FOLDER_BACKGROUND_IMGS/
fi

# Change ownership
arch-chroot $FOLDER_MNT /bin/bash -c "
  chown -R $user /$FOLDER_BACKGROUND_IMGS
  chgrp -R $user /$FOLDER_BACKGROUND_IMGS
"
# ------------------------------------------------------------------------------

source home/common/install

# Change ownership
arch-chroot $FOLDER_MNT /bin/bash -c "
  chown -R $user /home/$user/$FOLDER_INSTALL
  chgrp -R $user /home/$user/$FOLDER_INSTALL

  chown -R $user /home/$user/$FOLDER_CONFIG
  chgrp -R $user /home/$user/$FOLDER_CONFIG
"

echo "--------------------------------------------------------------------------------"
echo "Gnome settings"
ls -hal $FOLDER_MNT/home/$user/$FOLDER_INSTALL/
ls -hal $FOLDER_MNT/home/$user/$FOLDER_CONFIG/

echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
