#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

function InstallGnome() {
  if [[ -z "$gui" ]]; then
    Install "xorg"
  fi

  if [[ $gui == "gnome" ]]; then
    Install "gnome"
    EnableService "gdm"
  fi
}
