#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

function usage() {
  echo "Usage: $0 [OPTIONS]"
  echo "Options:"
  echo " [--gui | -g] gnome | dwm   Graphical user interface. Defaultly installs none."
}

function InstallGui() {
  if [[ $gui != "gnome" ]]; then
    # Inject "common" content after the 1st row into "gnome" file after the 1st row 
    script=$(sed "1r common" "gnome" | sed "1d")
    arch-chroot /mnt /bin/bash -c "echo $script | bash"
  fi
}

# ------------------------------------------------------------------------------
# Options
# ------------------------------------------------------------------------------

# Default values
gui="none"

if [[ $# -gt 0 ]]; then
  # Interpret options
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -g | --gui)
        gui=$2
        if [[ $gui != "gnome" ]] && [[ $gui != "dwm" ]]; then
          usage
          exit 1
        fi
        shift 2
        ;;
      *)
        echo "ERROR: Unknown option $1"
        usage
        exit 1
    esac
  done
fi

# ------------------------------------------------------------------------------
# Gui setup
# ------------------------------------------------------------------------------

InstallGui
