#!/bin/bash

function choose_dev_option() {
  echo "Please choose if development tools should be installed or not:"

  options=("Yes" "No" "Quit")

  select choice in "${options[@]}"; do
      case $choice in
          "Yes")
              development="true"
              break
              ;;
          "No")
              development="false"
              break
              ;;
          "Quit")
              echo "Exiting..."
              break
              ;;
          *)
              echo "Invalid option. Please try again."
              ;;
      esac
  done
}
