#!/bin/bash

# Install sound control
pacman -S pipewire pipewire-pulse wireplumber --noconfirm

# Install volume controller
pacman -S pavucontrol --noconfirm

# Install file manager
pacman -S pcmanfm --noconfirm

echo "--------------------------------------------------------------------------------"
echo "Install dwm specific apps"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
