#!/bin/bash

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------

source ../.common/configure
source xorg
source sound
source terminal
source build-essential

# ------------------------------------------------------------------------------
# Setup 
# ------------------------------------------------------------------------------

configure_globals
update_packages
install_xorg
install_build_essential
install_terminal
install_sound
echo "Setup was successful"
