#!/bin/bash

function install_xorg_debian() {
  install "xserver-xorg xinit xinput x11-xserver-utils xserver-xorg-core xserver-xorg-video-intel xserver-xorg-video-amdgpu"
}


function install_xorg_arch() {
  echo "not implemented yet!"
}

function install_xorg() {
  [[ $LINUX == "debian" ]] && install_xorg_debian
  [[ $LINUX == "arch" ]] && install_xorg_arch
}


