#!/bin/bash

set -- --boot bios --disk /dev/sda --gui gnome --user developer
source options/interpreter

source common/distro
source common/globals
source common/keys
source partition/create
source partition/format
source partition/mount



# base
InstallBaseLinux

# common
CreateEssentialFolders

# base
CreateFstab

ConfigureBaseSystem # $boot, $disk
InstallBaseSystemApps
SetupFirewall
ConfigureUser

# gui
InstallGui

# home/common
HomeConfigurations

# common
UmountPartitions
ShutdownSystem


source partition/umount

