#!/bin/bash

set -- --boot bios --disk /dev/sda --gui gnome --user developer
source options/interpreter
source common/distro
source common/globals

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------

# init
update_arch_keys

# partitions
create_partitions_$boot
FormatPartitions
MountPartitions

# base
InstallBaseLinux

# common
CreateEssentialFolders

# base
CreateFstab

ConfigureBaseSystem # $boot, $disk
InstallBaseSystemApps
SetupFirewall
ConfigureUser

# gui
InstallGui

# home/common
HomeConfigurations

# common
UmountPartitions
ShutdownSystem

