#!/bin/bash

set -- --boot uefi --disk /dev/sda --gui dwm --user developer --vboxutils flase --development true
source options/interpreter

source common/distro
source common/globals
source common/keys
source partition/create
source partition/format
source partition/mount
source base/install
source base/folders
source base/create-fstab
source base/chroot-install
source gui/chroot-install
source applications/install
source home/install
source partition/umount
shutdown -h now

