#!/bin/bash

set -- --boot uefi --disk /dev/sda --gui gnome --user zoltan --vboxutils false --luks true
source options/interpreter


source common/distro
source common/globals
source common/keys
source partition/create
source partition/format
source partition/mount
source base/install
source base/folders
source base/create-fstab
source base/chroot-install
source gui/chroot-install
source applications/pre-install
source applications/zoltan
source applications/development
source applications/post-install
source home/install
source partition/umount
shutdown -h now
