#!/bin/bash

# Download apps source code
function download_apps_sources() {
  clone "https://github.com/neovim/neovim" "install"
}

# Build neovim
function build_neovim() {
  local build_dir=/root/.install
  mkdir -p $build_dir
  mv -f $TMP/install/neovim $build_dir
  cd $build_dir/neovim

  git checkout stable
  make CMAKE_BUILD_TYPE=RelWithDebInfo
  make clean install
  cp $build_dir/neovim/build/bin/nvim /usr/bin
}

# Build applications from source
function build_apps_from_src() {
  local orig_path=$(pwd)

  download_apps_sources
  build_neovim

  cd $orig_path
}
