#!/bin/bash

# ------------------------------------------------------------------------------
# Command line options
#
#  setup: 
#  ------
#  Has to be impleneted by client script. It will be called if correct options 
#  were provided.
# ------------------------------------------------------------------------------

# Define a function to display script usage
function usage() {
  echo "Usage: $0 [OPTIONS]"
  echo "Options:"
  echo "  --linux arch | debian"
  exit 1
}

# Configure globals
function configure_globals() {
  declare -g TMP=/tmp

  if [[ $1 == "debian" ]]; then
    declare -g PACKAGE_MANAGER="apt install"
    declare -g NOCONFIRM="-y"
    declare -g BASE_DEVEL=build-essential
  else
    usage; exit;
  fi
}

# Parse command line options
[[ $# -gt 0 ]] || (usage; exit)

case "$1" in
  --linux)
    [[ $# -gt 1 ]] || (usage; exit)
    configure_globals $2
    setup # API: external method to be called
    ;;
  --help)
    usage
    shift 1
    ;;
  *)
    echo "Error: Unknown option $1"
    usage
    ;;
esac
