#!/bin/bash

# ------------------------------------------------------------------------------
# Global functions
# ------------------------------------------------------------------------------

function ConfigureGlobals() {
  . /etc/os-release                                         # Set linux distribution (debian | arch) into ID global
  export LINUX="$ID"                                        # Linux distribution
  export INSTALL_FOLDER=.install
  export CONFIG_FOLDER=.config
  export MNT_FOLDER=/mnt
  export TEMP_FILE=/tmp/tempfile
  export BACKGROUND_IMGS_FOLDER=/usr/share/backgrounds


  if [[ $LINUX != "arch" ]]; then
    echo "This installation does not work for the" $LINUX "distribution!"
    exit 1                                                  # Exit on wrong option
  fi
}

function UpdatePackages() { 
  pacman-key --init
  pacman-key --populate
  pacman -Sy archlinux-keyring --noconfirm
}

function Install() {
  packages=$1                                               # First argument: packages to be installed
  pacman -S $packages --noconfirm
}

function EnableService() {
  service=$1
  systemctl enable $service
}

function StartService() {
  service=$1
  systemctl start $service
}

function GitClone() {
  gitrepo=$1
  git clone ${gitrepo}
}

function GitHubClone() {
  gitrepo=$1
  target=.
  if [[ -n $2 ]]; then
    target=$2
  fi
  echo "target:" ${target}
  git clone https://github.com/${gitrepo} ${target}
}

function CreateEssentialFolders() {
  mkdir -p ${MNT_FOLDER}/root/${INSTALL_FOLDER}
  mkdir -p ${MNT_FOLDER}/root/${CONFIG_FOLDER}
}


# ------------------------------------------------------------------------------
# Partition related functions
# ------------------------------------------------------------------------------

function CreatePartitions() {
  if [[ $boot == "bios" ]]; then
    echo -e "o\nn\n\n\n\n\na\nw\n" | fdisk $disk
  fi 

  if [[ $boot == "uefi" ]]; then
    echo -e "g\nn\n\n\n+1G\nt\nuefi\nn\n\n\n\nw\n" | fdisk $disk
  fi
}

function FormatPartitions() {
  if [[ $boot == "bios" ]]; then
    mkfs.ext4 ${disk}1
  fi

  if [[ $boot == "uefi" ]]; then
    mkfs.fat -F 32 ${disk}1
    mkfs.ext4 ${disk}2
  fi
}

function MountPartitions() {
  if [[ $boot == "bios" ]]; then
    mount ${disk}1 ${MNT_FOLDER}
  fi

  if [[ $boot == "uefi" ]]; then
    mount ${disk}2 ${MNT_FOLDER}
    mount --mkdir ${disk}1 ${MNT_FOLDER}/boot/efi
  fi
}

function UmountPartitions() {
  umount -R ${MNT_FOLDER}
}

function ShutdownSystem() {
  shutdown -h now
}
