#!/bin/bash

echo "Please choose the installation profile:"

options=("Zoltán" "Quit")

select choice in "${options[@]}"; do
    case $choice in
        "Zoltán")
            profile=zoltan
            break
            ;;
        "Quit")
            echo "Exiting..."
            break
            ;;
        *)
            echo "Invalid option. Please try again."
            ;;
    esac
done

if [[ $choice != "Quit" ]]; then
  source ./profiles/"$profile"
fi
