#!/bin/bash

echo "Please choose the installation profile:"

options=("Customizable" "Development" "Zoltán" "Quit")

select choice in "${options[@]}"; do
    case $choice in
        "Customizable")
            profile=customizable
            break
            ;;
        "Development")
            profile=development
            break
            ;;
        "Zoltán")
            profile=zoltan
            break
            ;;
        "Quit")
            echo "Exiting..."
            break
            ;;
        *)
            echo "Invalid option. Please try again."
            ;;
    esac
done

if [[ $choice != "Quit" ]]; then
  source ./profiles/"$profile"
fi
