#!/bin/bash

echo "Please choose the installation profile:"

options=("Customizable" "Quit")

select choice in "${options[@]}"; do
    case $choice in
        "Customizable")
            echo "You chose Customizable option"
            ;;
        "Quit")
            echo "Exiting..."
            break
            ;;
        *)
            echo "Invalid option. Please try again."
            ;;
    esac
done
