#!/bin/bash

pacman-key --init
pacman-key --populate
pacman -Sy archlinux-keyring --noconfirm

echo "--------------------------------------------------------------------------------"
echo "Arch keys update ended"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
echo "--------------------------------------------------------------------------------"
