#!/bin/bash

# Copy .xinitrc into users folder
arch-chroot $FOLDER_MNT /bin/bash -c "
  cp ~/.xinitrc /home/$user/.xinitrc
"

echo "--------------------------------------------------------------------------------"
echo "Install DWM specific home setting"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
