#!/bin/bash

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------

source ../.common/configure
source app/install
source user/configure
source gui/install

# ------------------------------------------------------------------------------
# Setup 
# ------------------------------------------------------------------------------

configure_globals
update_packages
install_apps
configure_users
install_gui

echo "Setup was successful"
