#!/bin/bash

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------

source user/configure
source lib/configure
source app/install

# ------------------------------------------------------------------------------
# Setup 
# ------------------------------------------------------------------------------

configure_globals
update_packages
install_apps
configure_users
echo "Setup was successful"
