#!/bin/bash

# Install node manager
arch-chroot $FOLDER_MNT /bin/bash -c "
  curl -L https://bit.ly/n-install | bash -s -- -y 
  sed -i 's|\$HOME/n|\$HOME/.install/n|g' ~/.bashrc 

  mv ~/n ~/$FOLDER_INSTALL/ 
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  su - $user -c '/home/$user/$FOLDER_INSTALL/n/bin/npm install -g @openai/codex'
"

# Install docker
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S docker --noconfirm
  systemctl start docker
  systemctl enable docker

  pacman -S docker-compose --noconfirm

  echo \"alias up='sudo docker-compose up -d --build'\" >> ~/.bashrc
  echo \"alias down='sudo docker-compose down'\" >> ~/.bashrc
  echo \"alias ld='sudo docker ps'\" >> ~/.bashrc
  echo \"alias logs='sudo docker-compose logs'\" >> ~/.bashrc
"

# Install Postman
arch-chroot $FOLDER_MNT /bin/bash -c "
  curl -L https://dl.pstmn.io/download/latest/linux64 -o /tmp/Postman-linux-x64.tar.gz
  mkdir -p ~/$FOLDER_INSTALL
  tar -xzf /tmp/Postman-linux-x64.tar.gz -C ~/$FOLDER_INSTALL
  rm /tmp/Postman-linux-x64.tar.gz
  ln -sf /home/$user/$FOLDER_INSTALL/Postman/Postman /usr/bin/postman
  cat <<EOF > /usr/share/applications/postman.desktop
[Desktop Entry]
Name=Postman
Exec=postman
Icon=/home/$user/$FOLDER_INSTALL/Postman/app/resources/app/assets/icon.png
Type=Application
Categories=Development;
EOF
"

# Install virtual-box
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S linux-headers virtualbox --noconfirm
  usermod -aG vboxusers $user
"

# Install some image processing tools
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S gimp inkscape --noconfirm
"

# Clone darktable instead of installing from packages
arch-chroot $FOLDER_MNT /bin/bash -c "
  mkdir -p /home/$user/$FOLDER_INSTALL

  if [ -d /home/$user/$FOLDER_INSTALL/darktable ]; then
    cd /home/$user/$FOLDER_INSTALL/darktable && git pull
  else
    git clone --depth 1 --recurse-submodules https://github.com/darktable-org/darktable /home/$user/$FOLDER_INSTALL/darktable
  fi

  chown -R $user:$user /home/$user/$FOLDER_INSTALL
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  su - $user -c 'cd /home/$user/$FOLDER_INSTALL/darktable && ./build.sh'
  ln -sf /home/$user/$FOLDER_INSTALL/darktable/build/bin/darktable /usr/bin/darktable
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  cat > /usr/share/applications/darktable.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=darktable
Exec=darktable
Icon=/home/$user/$FOLDER_INSTALL/linux/arch/install/home/common/gnome/.config/darktable.png
Terminal=false
Categories=Graphics;Photography;
EOF
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S libreoffice --noconfirm
"

echo "--------------------------------------------------------------------------------"
echo "Install development environment"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
