#!/bin/bash

# Install virtual-box
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S linux-headers virtualbox --noconfirm
  usermod -aG vboxusers $user
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S firefox --noconfirm
"

# Install some image processing tools
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S gimp inkscape --noconfirm
"

# Clone darktable instead of installing from packages
arch-chroot $FOLDER_MNT /bin/bash -c "
  mkdir -p /home/$user/.install

  if [ -d /home/$user/.install/darktable ]; then
    cd /home/$user/.install/darktable && git pull
  else
    git clone --depth 1 https://github.com/darktable-org/darktable /home/$user/.install/darktable
  fi

  chown -R $user:$user /home/$user/.install
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S libreoffice --noconfirm
"

echo "--------------------------------------------------------------------------------"
echo "Install applications for $profile profile"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
