#!/bin/bash

# Install virtual-box
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S linux-headers virtualbox --noconfirm
  usermod -aG vboxusers $user
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S libreoffice --noconfirm
"

echo "--------------------------------------------------------------------------------"
echo "Install applications for $profile profile"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
