#!/bin/bash

# Install virtual-box
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S linux-headers virtualbox --noconfirm
  usermod -aG vboxusers $user
"

# Install some image processing tools
arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S gimp inkscape --noconfirm
"

# Clone darktable instead of installing from packages
arch-chroot $FOLDER_MNT /bin/bash -c "
  mkdir -p /home/$user/$FOLDER_INSTALL

  if [ -d /home/$user/$FOLDER_INSTALL/darktable ]; then
    cd /home/$user/$FOLDER_INSTALL/darktable && git pull
  else
    git clone --depth 1 --recurse-submodules https://github.com/darktable-org/darktable /home/$user/$FOLDER_INSTALL/darktable
  fi

  chown -R $user:$user /home/$user/$FOLDER_INSTALL
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  su - $user -c 'cd /home/$user/$FOLDER_INSTALL/darktable && ./build.sh'
  ln -sf /home/$user/$FOLDER_INSTALL/darktable/build/bin/darktable /usr/bin/darktable
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  cat > /usr/share/applications/darktable.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=darktable
Exec=darktable
Icon=/home/$user/$FOLDER_INSTALL/linux/arch/install/assets/darktable.png
Terminal=false
Categories=Graphics;Photography;
EOF
"

arch-chroot $FOLDER_MNT /bin/bash -c "
  pacman -S libreoffice --noconfirm
"

echo "--------------------------------------------------------------------------------"
echo "Install applications for $profile profile"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
