#!/bin/bash

# Clones resources
function download_git_repos() {
  clone "https://github.com/devbysp/nvim" "config"
}

# Copy cloned resource from tmp folder to root folder
function copy_root_dot_files() {
  mkdir -p /root/.config
  cp -r $TMP/config/nvim /root/.config
}

# Copy cloned resource from tmp folder to user home folder
function copy_user_dot_files() {
  mkdir -p /home/$USER/.config
  cp -r $TMP/config/nvim /home/$USER/.config
}

# Restores dotfiles
function restore_dotfiles() {
  local orig_path=$(pwd)

  download_git_repos
  copy_user_dot_files
  copy_root_dot_files

  cd $orig_path
  rm -r $TMP/config
}

