#!/bin/bash

# Network manager to have access to the internet
Install "networkmanager"
EnableService "NetworkManager"

# Git to be able to clone the home manager repo
Install "git"

# return success
exit 0
