#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------
function ConfigureFirewall() {
  ufw default deny outgoing
  ufw default deny incoming
  ufw default deny routed

  ufw allow out http
  ufw allow out https
  ufw allow out dns
  ufw allow out ssh

  systemctl enable ufw
  systemctl start ufw

  ufw enable 
}


# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# Network manager to have access to the internet
Install "networkmanager"
EnableService "NetworkManager"

# Git to be able to clone the home manager repo
Install "git"

# Basic build tools
# Install "base-devel make gcc"

# return success
exit 0
