#!/bin/bash

function InstallBaseLinux() {
  pacstrap -K /mnt base linux linux-firmware --noconfirm
}

function CreateFstab() {
  genfstab -U /mnt > /mnt/etc/fstab
}

function ConfigureBaseSystem() {
  script=$(sed "3 i\boot=$boot\n" configure)
  arch-chroot /mnt /bin/bash -c "echo $script | bash"
}

function InstallBaseSystemApps() {
  script=$(sed "1r common" "apps" | sed "1d")
  mount --rbind /lib/modules /mnt/lib/modules

  arch-chroot /mnt /bin/bash -c "echo $script | bash"
}
