#!/bin/bash

Install "ufw"
EnableService "ufw"

systemclt start ufw

ufw default deny outgoing
ufw default deny incoming
ufw default deny routed

ufw allow out http
ufw allow out https
ufw allow out dns

ufw enable
ufw status
