#!/bin/bash

#
# It depends on the "apps, user" scripts
#

function InstallBaseLinux() {
  pacstrap -K /mnt base linux linux-firmware --noconfirm
}

function CreateFstab() {
  genfstab -U /mnt > /mnt/etc/fstab
}

function ConfigureBaseSystem() {
  script=$(sed "3 i\boot=$boot\n" configure)
  arch-chroot /mnt /bin/bash -c "echo $script | bash"
}

function InstallBaseSystemApps() {
  # It depends on the "apps" script
  script=$(sed "1r common" "apps" | sed "1d")
  mount --rbind /lib/modules /mnt/lib/modules

  arch-chroot /mnt /bin/bash -c "echo $script | bash"
}

function ConfigureUser() {
  # It depends on the "user" script
  script=$(sed "1r common" "user" | sed "1d" | sed "3 i\user=$user")
  arch-chroot /mnt /bin/bash -c "echo $script | bash"
}
