#!/bin/bash

function InstallBaseLinux() {
  pacstrap -K /mnt base linux linux-firmware $NOCONFIRM
}

function CreateFstab() {
  genfstab -U /mnt > /mnt/etc/fstab
}

function ConfigureBaseSystem() {
  script=$(cat base-system-configure)
  arch-chroot /mnt /bin/bash -c $script
}

function InstallBaseSystemApps() {
  script=$(sed '1r common' 'base-system-apps' | sed '1d')
  arch-chroot /mnt /bin/bash -c $script
}

function ConfigureBaseSystemSecurity() {
  script=$(sed '1r common' 'base-system-security' | sed '1d')
  arch-chroot /mnt /bin/bash -c $script
}
