#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

function ConfigureFirewall() {
  ufw default deny outgoing
  ufw default deny incoming
  ufw default deny routed

  ufw allow out http
  ufw allow out https
  ufw allow out dns
  ufw allow out ssh

  EnableService "ufw"
  StartService "ufw"

  ufw enable 
}

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# Firewall
Install "ufw"
ConfigureFirewall

# return success
exit 0
