#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

function ConfigureFirewall() {
  ufw default deny outgoing
  ufw default deny incoming
  ufw default deny routed

  ufw allow out http
  ufw allow out https
  ufw allow out dns
  ufw allow out ssh

  systemctl enable ufw
  systemctl start ufw

  ufw enable 
}

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# Firewall
Install "ufw"
ConfigureFirewall

exit 0
