#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

function InstallGui() {
  echo "gui:" $gui

  if [[ $gui == "gnome" ]] || [[ $gui == "dwm" ]]; then
    echo "pwd: " $(pwd)
    ../Gui/gui --gui $gui
  else
    ../Gui/gui
  fi

  echo "Press Enter to continue..."
  read  # Waits for user to press Enter

}
