#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

function InstallGui() {
  if [[ $gui == "gnome" ]]; then
    # Inject "common" content after the 1st row into "gnome" file after the 1st row 
    script=$(sed "1r common" "gnome" | sed "1d")
    arch-chroot /mnt /bin/bash -c "echo $script | bash"
  fi

  if [[ $gui == "dwm" ]]; then
    # Inject "common" content after the 1st row into "dwm" file after the 1st row 
    script=$(sed "1r common" "dwm" | sed "1d")
    arch-chroot /mnt /bin/bash -c "echo $script | bash"
  fi
}
