#!/bin/bash

source common
source base

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------

ConfigureGlobals
UpdatePackages

CreatePartitions
FormatPartitions
MountPartitions

InstallBaseLinux
CreateFstab
ConfigureBaseSystem
InstallBaseSystemApps

CopySetupScript
UmountPartitions
ShutdownSystem
