#!/bin/bash

source common
source base

# ------------------------------------------------------------------------------
# Options
# ------------------------------------------------------------------------------

# Display script usage
function usage() {
  echo "Usage: $0 [OPTIONS]"
  echo "Options:"
  echo " [--user | -u] <user>               The user to be created. It is a mandatory field." 
  echo " [--boot | -b] bios | uefi          The boot mode to be installed. Default value is uefi."
}

# Default values
boot="uefi"
user=""

if [[ $# -gt 0 ]]; then
  # Interpret options
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -b | --boot)
        boot=$2
        if [[ $boot != "bios" ]] && [[ $boot != "uefi" ]]; then
          usage
          exit 1
        fi
        shift 2
        ;;
      -u | --user)
        user=$2
        if [[ -z "$user" ]]; then
          usage
          exit 1
        fi
        shift 2
        ;;
      *)
        echo "ERROR: Unknown option $1"
        usage
        exit 1
    esac
  done
fi

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------

ConfigureGlobals
UpdatePackages

CreatePartitions
FormatPartitions
MountPartitions

InstallBaseLinux
CreateFstab
ConfigureBaseSystem
InstallBaseSystemApps
ConfigureUser

CopySetupScript
UmountPartitions

ShutdownSystem
