#!/bin/bash

# Install sudo
function InstallSudo() {
  Install "sudo"
}

# Create user
function CreateUser() {
  sudo useradd --create-home --shell /bin/bash $user
}

# Set password
function SetPassword() {
  password="changeit"
  echo -en "$password\n$password\n" | sudo passwd $user
}

# Add user to sudoers
function AddUserToSudoers() {
  sudo usermod -aG wheel "$user"
  sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/g' /etc/sudoers
}

# Disable root user
function DisableRoot() {
  sudo passwd -d root
  sudo passwd -l root
}

# User related configurations
InstallSudo
CreateUser
SetPassword
AddUserToSudoers
DisableRoot
