#!/bin/bash

# Minimal X server running on a Linux system
#  - xorg-server: provides the infrastructure for creating and managing graphical user interfaces
#  - xorg-xinit: starts the X server and loads config from .xinitrc
#  - xorg-xrandr: hotplug, screen resolution, rotation, orientation ...
#  - xset-root: set the root window properties of the X server.
#    - background color:\> xsetroot -solid black
#    - background image:\> xsetroot -bitmap /path/to/background.png
pacman -S xorg-server xorg-xinit xorg-xrandr xorg-xsetroot --noconfirm

#  - libx11: provides the basic functionality for communicating with the X Window System server.
#  - libxinerama: nables multiple physical monitors to be treated as a single, logical display.
#  - libfxt: rendering fonts in graphical applications
pacman -S libx11 libxinerama libfxt --noconfirm

# It provides a set of libraries and tools for embedding web content in GTK+ applications. It is needed to start dwm.
pacman -S webkit2gtk --noconfirm

# Graphical card driver
pacman -S mesa --noconfirm
pacman -S xf86-video-ati --noconfirm      # AMD
pacman -S xf86-video-intel --noconfirm    # Intel
pacman -S xf86-video-nvidia --noconfirm   # NVIDIA

# Nerd fonts
pacmna -S ttf-ubuntu-mono-nerd --noconfirm

# ------------------------------------------------------------------------------
# Create xinit config
# ------------------------------------------------------------------------------
touch ~/.xinitrc

echo 'setxkbmap hu -model "pc101" -variant "101_qwerty_comma_dead" &' >> ~/.xinitrc
echo 'xrandr --output Virtual-1 --mode 1920x1080 &' >> ~/.xinitrc
echo 'slstatus &' >> ~/.xinitrc
echo 'xsetroot -solid "#101e26" &' >> ~/.xinitrc
echo 'exec dwm' >> ~/.xinitrc

# ------------------------------------------------------------------------------
# Install Dynamic Window Manager
# ------------------------------------------------------------------------------
config_header=config.def.h
mkdir -p ~/$FOLDER_INSTALL/dwm

cd ~/$FOLDER_INSTALL/dwm
git clone https://git.suckless.org/dwm

cd ~/$FOLDER_INSTALL/dwm/dwm

# Set default font
sed -i 's/\(.*\)col_cyan\[\]\( *\)= "#\([0-9]\{6\}\)";/\1col_cyan[]\2= "#1d2133";/g' $config_header
make clean install

# ------------------------------------------------------------------------------
# Install Simple Terminal
# ------------------------------------------------------------------------------
cd ~/$FOLDER_INSTALL/dwm
git clone https://git.suckless.org/st

cd ~/$FOLDER_INSTALL/dwm/st

# Add color scheme feature available by applying the colorschemes patch
patch=$(curl -s https://st.suckless.org/patches/colorschemes/ | grep -o 'st-colorschemes-[0-9\.]*\.diff' | head -n 1)
curl -s https://st.suckless.org/patches/colorschemes/${patch} | git apply

# Makes 'Alacritty (dark)' color scheme dafault by moving it to the first position in the scheme list
target_line=$(grep -n "static const ColorScheme schemes" $config_header | cut -d':' -f1)
start_line=$(grep -n "Alacritty (dark)" $config_header | cut -d':' -f1)
end_line=$(expr ${start_line} + 6)

sed -n "${start_line},${end_line}w $FILE_TEMP" $config_header
sed -i "${start_line},${end_line}d" $config_header
sed -i "${target_line}r $FILE_TEMP" $config_header
rm $FILE_TEMP

# Change terminal font to FreeMono:16
sed -i 's/\(.*\)font = ".*:pixelsize=12\(.*\)";/\1font = "UbuntuMono:pixelsize=16\2";/g' $config_header
make clean install

# ------------------------------------------------------------------------------
# Install dmenu
# ------------------------------------------------------------------------------
cd ~/$FOLDER_INSTALL/dwm
git clone https://git.suckless.org/dmenu

cd ~/$FOLDER_INSTALL/dwm/dmenu
make clean install

# ------------------------------------------------------------------------------
# Install sltatus
# ------------------------------------------------------------------------------
cd ~/$FOLDER_INSTALL/dwm
git clone https://git.suckless.org/slstatus

cd ~/$FOLDER_INSTALL/dwm/slstatus

# Configure status
# Source for icons: https://www.nerdfonts.com/cheat-sheet
sed -i 's/\(.*\)datetime,\(.*\)$/  { cpu_perc, "   %s%% |", NULL }, { ram_used, "   %s", NULL }, { ram_perc, " \(%s%%\) \/", NULL }, { ram_total, " %s |", NULL }, { disk_used, "   %s", "\/" }, { disk_perc, " \(%s%%\) \/", "\/" }, { disk_total, " %s |", "\/" }, { datetime, " %s ", "%A %d | %H:%M" }/g' $config_header
make clean install

echo "--------------------------------------------------------------------------------"
echo "dwm has been installed"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
echo "--------------------------------------------------------------------------------"
