#!/bin/bash

pacman -S xorg gnome --noconfirm
systemctl enable gdm

echo "--------------------------------------------------------------------------------"
echo "Gnome has been installed"
echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
