#!/bin/bash

PROFILE_DCONF=home/profiles/$profile/$gui/$FOLDER_CONFIG/dconf
COMMON_DCONF=home/common/$gui/$FOLDER_CONFIG/dconf

if [[ -e $PROFILE_DCONF ]]; then
  cp -r $PROFILE_DCONF    $FOLDER_MNT/home/$user/$FOLDER_CONFIG/
else
  cp -r $COMMON_DCONF     $FOLDER_MNT/home/$user/$FOLDER_CONFIG/
fi

MONITORS_CONFIG=.config/monitors.xml
PROFILE_MONITORS_CONFIG=home/profiles/$profile/$MONITORS_CONFIG

if [[ -e $PROFILE_MONITORS_CONFIG ]]; then
  cp $PROFILE_MONITORS_CONFIG $FOLDER_MNT/home/$user/$MONITORS_CONFIG
fi

GDM_CONFIG=etc/gdm/custom.conf
PROFILE_GDM_CONFIG=home/profiles/$profile/$GDM_CONFIG

if [[ -e $PROFILE_GDM_CONFIG ]]; then
  cp $PROFILE_GDM_CONFIG $FOLDER_MNT/$GDM_CONFIG
fi

echo "--------------------------------------------------------------------------------"
echo "Install Gnome specific home setting"
ls $FOLDER_MNT/home/$user/$FOLDER_CONFIG/
ls $FOLDER_MNT/$FOLDER_BACKGROUND_IMGS
cat $FOLDER_MNT/$PROFILE_GDM_CONFIG

echo "Press Enter to  ontinue, or wait 5 seconds..."
read -t 5 -n 1  # Wait for 5 seconds or a single keypress
