#!/bin/bash

function create_partitions() {
  if [[ "$luks" == "true" ]]; then
    echo -e "g\nn\n\n\n\n+1G\nt\nboot\nn\n\n\n\na\n1\nw\n" | fdisk $disk
  else
    echo -e "o\nn\n\n\n\n\na\nw\n" | fdisk $disk
  fi

  echo "--------------------------------------------------------------------------------"
  echo "Partitions on '$disk' device have been created" 
  fdisk --list $disk

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

function format_partitions() {
  if [[ "$luks" == "true" ]]; then
    mkfs.ext4 ${disk}1
    echo -n "$luks_password" | cryptsetup luksFormat ${disk}2 -
    echo -n "$luks_password" | cryptsetup open ${disk}2 cryptroot -
    mkfs.ext4 /dev/mapper/cryptroot
    cryptsetup close cryptroot
  else
    mkfs.ext4 ${disk}1
  fi

  echo "--------------------------------------------------------------------------------"
  echo "Partitions on '$disk' device have been formatted" 
  lsblk --fs $disk

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

function mount_partitions() {
  if [[ "$luks" == "true" ]]; then
    echo -n "$luks_password" | cryptsetup open ${disk}2 cryptroot -
    mount /dev/mapper/cryptroot $FOLDER_MNT
    mount --mkdir ${disk}1 $FOLDER_MNT/boot
  else
    mount ${disk}1 $FOLDER_MNT
  fi

  echo "--------------------------------------------------------------------------------"
  if [[ "$luks" == "true" ]]; then
    echo "Partition '${disk}2' has been opened as cryptroot and mounted on $FOLDER_MNT"
    echo "Partition '${disk}1' has been mounted on $FOLDER_MNT/boot"
  else
    echo "Partition '${disk}1' has been mounted on $FOLDER_MNT"
  fi

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

function umount_partitions() {
  if [[ "$luks" == "true" ]]; then
    umount -R $FOLDER_MNT/boot
  fi
  umount -R $FOLDER_MNT
  if [[ "$luks" == "true" ]]; then
    cryptsetup close cryptroot
  fi

  echo "--------------------------------------------------------------------------------"
  if [[ "$luks" == "true" ]]; then
    echo "Partition '${disk}1' has been umounted from $FOLDER_MNT/boot"
    echo "cryptroot has been closed and unmounted from $FOLDER_MNT"
  else
    echo "Partition '${disk}1' has been umounted from $FOLDER_MNT"
  fi

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

