#!/bin/bash

function create_partitions() {
  echo -e "g\nn\n\n\n+1G\nt\nuefi\nn\n\n\n\nw\n" | fdisk $disk

  echo "--------------------------------------------------------------------------------"
  echo "Partitions on '$disk' device have been created" 
  fdisk --list $disk

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

function format_partitions() {
  mkfs.fat -F 32 ${disk}1

  if [[ "$luks" == "true" ]]; then
    echo -n "$luks_password" | cryptsetup luksFormat ${disk}2 -
    echo -n "$luks_password" | cryptsetup open ${disk}2 cryptroot -
    mkfs.ext4 /dev/mapper/cryptroot
    cryptsetup close cryptroot
  else
    mkfs.ext4 ${disk}2
  fi

  echo "--------------------------------------------------------------------------------"
  echo "Partitions on '$disk' device have been formatted" 
  lsblk --fs $disk

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

function mount_partitions() {
  if [[ "$luks" == "true" ]]; then
    echo -n "$luks_password" | cryptsetup open ${disk}2 cryptroot -
    mount /dev/mapper/cryptroot $FOLDER_MNT
  else
    mount ${disk}2 $FOLDER_MNT
  fi
  mount --mkdir ${disk}1 $FOLDER_MNT/boot

  echo "--------------------------------------------------------------------------------"
  if [[ "$luks" == "true" ]]; then
    echo "Partition '${disk}2' has been opened as cryptroot and mounted on $FOLDER_MNT"
  else
    echo "Partition '${disk}2' has been mounted on $FOLDER_MNT"
  fi
  echo "Partition '${disk}1' has been mounted on $FOLDER_MNT/boot/efi"

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}

function umount_partitions() {
  umount -R $FOLDER_MNT/boot/efi
  umount -R $FOLDER_MNT
  if [[ "$luks" == "true" ]]; then
    cryptsetup close cryptroot
  fi

  echo "--------------------------------------------------------------------------------"
  echo "Partition '${disk}1' has been umounted from $FOLDER_MNT/boot/efi"
  if [[ "$luks" == "true" ]]; then
    echo "cryptroot has been closed and unmounted from $FOLDER_MNT"
  else
    echo "Partition '${disk}2' has been umounted from $FOLDER_MNT"
  fi

  echo "Press Enter to  ontinue, or wait 5 seconds..."
  read -t 5 -n 1  # Wait for 5 seconds or a single keypress
}


